remove the plotnine dependency and update related function
arup-group/elara pull request #226
Opened 2022-11-30 16:57 UTC by syhwawa

Since the plotnine dependency produced multiple dependency conflicts([issue #225](https://github.com/arup-group/elara/issues/225)), and the conflict/bug is not straightforward to capture. I have changed the related plotnine functions using matplotlib instead and remove the dependency. 

I think the changes affect some comparison plots like link counter comparison. The new comparison plot look like more consistent with other comparison plots since they all use matplotlib. Not sure why it used ggplot from plotnine previously but we can add plot style as 'ggplot' if we would like to. 

New plot via matplotlib: 
![link_counter_comparison_car_B_summary_normalised](https://user-images.githubusercontent.com/58612648/204857513-16a08c6a-77ec-434a-8c1e-a659226a2f47.png)

old ggplot via plotnine:
![link_counter_comparison_car_B_summary_normalised_old](https://user-images.githubusercontent.com/58612648/204858013-06d633be-9cce-4bb1-987e-64766b588703.png)

There is a quite old mode share comparison function `OldModeSharesComparison` based on another plot functions via plot nine. I think we are using `TripModeSharesComparison ` to show the mode share differences instead of the old function so I just remove it.

2022-11-30 19:57 UTC, andkay requested changes
nice one @syhwawa -- and good catch removing the unused `plot_comparison_bar` function. 

i don't see a good reason to use the matplot ggplot style if it's' inconsistent with other benchmarks.  however, i do think its worth adding the vertical and horizontal gridlines to this plot to make it easier to read.  you might need to call `set_axisbelow` method to make sure these appear behind the chart rather than in front.

2022-12-01 15:45 UTC, andkay approved these changes
👍🏼

2022-12-01 15:50 UTC, syhwawa commented
Good point @andkay. I think the gridlines are useful, so I added them to the plot.
![examples](https://user-images.githubusercontent.com/58612648/205097395-0b05e235-aaf3-4fbf-87cd-9d11ab67e979.png)

2022-12-02 19:30 UTC, merged

2022-12-05 10:35 UTC, fredshone commented
Thanks for picking this up - Nice job :)