creates project specific logger
arup-group/elara pull request #233
Opened 2023-06-23 12:31 UTC by fredshone

fixes #150 by changing to a "project specific logger" in main, rather than calling the default. This prevents setting the underlying dependancy loggers to debug. I have tested locally.

I've also changed the config key from `verbose` to `debug`. I feel this more accurately reflects the option. Old configs with `verbose = true` will still work but elara will silently revert to debug = false. Normally i would think this is dodgy, but in this case I think it is appropriate.

Docs and examples updated.

2023-06-23 13:19 UTC, syhwawa commented on example_configs/config.toml
> +verbose = true
In the fixed code,  Will `debug = false
verbose = true` in the config be equivalent to `debug = false` by setting level to debug?

2023-06-23 13:21 UTC, syhwawa reviewed
Nice job!  

I am wondering if it will be easy to use the existing function [here](https://github.com/arup-group/elara/blob/main/elara/config.py#L336C2-L358) to set different logging levels without introducing two parameters? 

For example, `verbose=info` representing the loggings will be on INFO level
`verbose=debug` representing the loggings will be on DEBUG level

2023-06-23 13:31 UTC, mfitz requested changes
The logging config change looks fine, although it would be nice to see more evidence of how you tested it locally and what happened.

On a different note - this is a user-facing change. If I'm understanding correctly, it's backwards compatible rather than breaking, but it's still a change that affects the user. As such, I think this is a minor version bump. Just looking at the current version: `__version__ = "0.0.0"`. I think this moves it to `"0.1.0"`.

Now might be a good time to create a `CHANGELOG.md` too (see [here](https://keepachangelog.com/en/1.1.0/) for a template), and to create a GitHub release.

2023-06-23 14:28 UTC, fredshone commented on example_configs/config.toml
> +verbose = true
yes, I treat verbose as synonymous with debug (perhaps more like "debug mode"). So `verbose = false` same as `debug = false` and vice versa.

2023-06-23 14:30 UTC, fredshone commented on example_configs/config.toml
> +verbose = true
I change to "debug" because the expectation is that you would set this to false unless you are actually debugging. Whereas "verbose" sounded more casual.

Basically i expect this to nearly always be false.

2023-06-23 14:32 UTC, fredshone commented
> Nice job!
> 
> I am wondering if it will be easy to use the existing function [here](https://github.com/arup-group/elara/blob/main/elara/config.py#L336C2-L358) to set different logging levels without introducing two parameters?
> 
> For example, `verbose=info` representing the loggings will be on INFO level `verbose=debug` representing the loggings will be on DEBUG level

well spotted! I changed the docs to push people to use either true or false. but it will also support specific levels. But I don't think really need to expose this to anyone.

2023-06-23 14:46 UTC, fredshone commented
> The logging config change looks fine, although it would be nice to see more evidence of how you tested it locally and what happened.
> 
> On a different note - this is a user-facing change. If I'm understanding correctly, it's backwards compatible rather than breaking, but it's still a change that affects the user. As such, I think this is a minor version bump. Just looking at the current version: `__version__ = "0.0.0"`. I think this moves it to `"0.1.0"`.
> 
> Now might be a good time to create a `CHANGELOG.md` too (see [here](https://keepachangelog.com/en/1.1.0/) for a template), and to create a GitHub release.

I tested by creating a "verbose" example config then checked to see if the "eroneous" logging is removed in the new branch. I say "locally" because as noted in the #150 behaviour does seem to vary my environment, most likely due to loose dependancies or sketch dev installs 🦡 .

So happy if others want to check.

This PR will silently make all existing state machine configs "quiet", which means we might be hiding weird behaviour on box. But the expectation is that no one will be running debug on a box in any case. Certainly not "unsupervised".

I have added Change log but then removed release note - I do not want the duplication on a project that is entering retirement.

2023-07-11 10:51 UTC, fredshone commented
Since also tested on our infra. Merging

2023-07-11 10:51 UTC, merged